### ISSUE TITLE
issue during installation

### ISSUE THREAD

**Issue by KarlLaue** [drmenzelit/nature-j4-template#10]
First of all, many thanks for the template. It looks nice. 
I tried to install it, but got a error message “Die Manifest-Datei konnte nicht gefunden werden.“
Any idea why?

Many thanks 
Thomas

**Comment by drmenzelit** [comment]
Did you downloaded the last release? https://github.com/drmenzelit/nature-j4-template/releases

**Comment by KarlLaue** [comment]
Yes, I did

**Comment by drmenzelit** [comment]
That is weird... I installed the template some days ago on a new Joomla instance without problems... Do you have problems with other extensions too?

**Comment by KarlLaue** [comment]
Sorry Not tested so far

**Comment by KarlLaue** [comment]
One question, is it possible to upload the missing file manually? If yes, which one and in which folder?
Again, many thanks for your help…..

**Comment by drmenzelit** [comment]
No, the installation should work without problems. I just installed it again on a Joomla instance and it worked.
You can try other ways:
- copy the zip into the tmp folder and use the "install from folder" tab
- unzip the template locally and upload it to the server (under templates), then go to System -> Discover

**Comment by KarlLaue** [comment]
It seems to work….. will check details during the weekend… thanks for your quick help….. have a nice weekend 
Thomas
