### ISSUE TITLE
Sample Data

### ISSUE THREAD

**Issue by tanjastern18** [drmenzelit/nature-j4-template#13]
Hello Viviana, I like your nature template very much and want to use it. But I`m missing sample data. For instance I would like to use the timeline but don`t know how. Or can I try the 4 styles you suggested? Maybe I didn`t download the right version?

Regards Tanya

**Comment by tanjastern18** [comment]
Oh sorry - now I catched how to use the timeline with the newsflash module. However, a little presetting would be nice.

Tanya

**Comment by drmenzelit** [comment]
Sorry for the belated answer. In the demo site there is already some information, about how to use Nature
https://j4.dr-menzel-it.de/about-nature/modules
I will add more explanations about the styles, but in principle there are copies of the template (now you can use child templates) with different settings for colors and using a blog layout also with different settings.
