### ISSUE TITLE
How can I add/change a new font ?

### ISSUE THREAD

**Issue by mariantanase** [drmenzelit/nature-j4-template#3]
Hi,
Congrats for this J4 clean template.
How can I use the "Titillium Web" font as a base font for a new style ?

**Comment by drmenzelit** [comment]
Thank you!

To use another font, you can create a user.css file and add there the definitions for the font (`@font-face...` , you can have a look at the files `css/global/fonts-...`)

and then overwrite the css variables like this:

`:root {
    --font-family-body: "Titillium Web",sans-serif;
    --font-family-headings: "Titillium Web",sans-serif;
    --font-weight-headings: 600;
    --font-weight-normal: 300;
}`

**Comment by mariantanase** [comment]
Allready done that. On my **user.css** I added the following lines:
```
@import url('https://fonts.googleapis.com/css2?family=Titillium+Web:wght@400;600&display=swap');
:root { 
	--font-family-body: "Titillium Web",sans-serif; 
	--font-family-headings: "Titillium Web",sans-serif; 
	--font-weight-headings: 600; 
	--font-weight-normal: 400; 
}
```
Great !
