### ISSUE TITLE
Color picker doesn't save the new color

### ISSUE THREAD

**Issue by mariantanase** [drmenzelit/nature-j4-template#4]
I published a newsflash module on top-a (nature) position.
I've done the following stepr:
1. Template Style > Nature Site Template > Position (tab) 
2. Select with color picker a new color for "Top A background color" > Save.
3. Result: The background color doesn't changed.
![Screenshot 2021-10-05 at 08-46-42 Templates Edit Style - Joomla 4 - Administration](https://user-images.githubusercontent.com/3976174/135973768-e855e74d-17e6-4a71-992e-084d90848bba.png)

**Comment by drmenzelit** [comment]
the colours are 'rgba', you need to change the transparency value too, standard is full transparent (0)

**Comment by mariantanase** [comment]
Yes, you're right!
I've modified value with something like: rgba(250, 242, 130, 0.4) and it's fine. Would be better to add some tooltips or messages. This accessible template is really very nice .
How can I help you to improve it?

**Comment by drmenzelit** [comment]
If you have suggestions, you can write me or make a PR. And I would be very thankful if you test the template with so many views as possible :-)

**Comment by mariantanase** [comment]
ok.
Starting from this issue, it's possible when user pick a color to save that color without transparency ?
Because in my opinion, the user expects to see the selected color.
(eg. default="rgba(255, 255, 255, 1)". And if he/she wants some transparency, will be inform how to modify it.
