### ISSUE TITLE
Problem with hamburger menu

### ISSUE THREAD

**Issue by Vidarico** [drmenzelit/nature-j4-template#6]
I installed only the latest version of joomla with demo data.
The menu does not work properly.

![1](https://user-images.githubusercontent.com/94024824/141030908-c19f6822-4cee-49a3-b36a-d05bc2d97874.jpg)
![2](https://user-images.githubusercontent.com/94024824/141030925-cb678104-9c31-40bc-8f4d-b224cce41135.jpg)

On the template configuration, the hamburger menu switch does not help.
![3](https://user-images.githubusercontent.com/94024824/141030961-6c7fbb7d-18dd-4cbd-a46b-9a876aa172fd.jpg)

You can see for yourself on the website for testing - http://a0564331.xsph.ru/

**Comment by drmenzelit** [comment]
You need to change the layout on the menu module. Select the layout from the template and not the standard from Joomla

**Comment by Vidarico** [comment]
It worked.
Thanks for your work!
