### ISSUE TITLE
How to load Bootstrap?

### ISSUE THREAD

**Issue by brettvac** [drmenzelit/nature-j4-template#7]
I noticed that my bootstrap containers aren't working with this template. How do I load bootstrap 5 with this template? Thanks.

**Comment by brettvac** [comment]
After poking around a bit, I added this

    JHtml::_('bootstrap.loadCss', true);

to the index.php file and that seemed to load bootstrap. My containers now display properly. Is that all I need to do? Should I create an override ?

**Comment by drmenzelit** [comment]
The idea behind of this template was not to use Bootstrap :-) So you will need to make an override or a copy of the template if you want to use Bootstrap.
