### ISSUE TITLE
Timeline does not show links nor "read more" button

### ISSUE THREAD

**Issue by JdLEL** [drmenzelit/nature-j4-template#9]
Hi,
I would like to use the Timeline feature in the template, but when I activate it, no links or "read more" buttons are added to the articles, although these options are selected in the backend.

Actions taken:
- activated module "Newsflash"
- selected "Timeline" option on advanced tab
- selected "show read more link" as well as "link article title"

Result:
- Timeline is nicely shown
- Titles of articles are NOT linked to full article
- Read more button is not shown

When I swap Timeline view for the default view, both links are shown and working.
Hope you will be able to solve this?
Thanks in advance.

**Comment by drmenzelit** [comment]
The timeline was not intended to link to the full article. But I can try to add the function to the override.

**Comment by JdLEL** [comment]
> The timeline was not intended to link to the full article. But I can try to add the function to the override.

Ah, missed that part that it was not intended to link to the full article.
Expected that it was a replacement for the default newsflash module.

Would be great if it can be added; but if not, I will find another way of showing my articles.

**Comment by drmenzelit** [comment]
The new version of the template includes a "read more" button for the timeline.
